# Generated by Django 6.0.6 on 2026-06-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_artist_genre_alter_song_artist_alter_song_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='energy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='popularity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
